### ISSUE TITLE
Lack of timeout for requests can cause queries to hang

### ISSUE THREAD

**Issue by bltravis** [library-data-platform/ldlite#1]
In trying to build an automated harvesting script for our production tenant, I've repeatedly encountered an issue where a query (particularly to the inventory-storage endpoints) will hang during the "reading" phase and require a keyboard interrupt to exit. Perhaps we could add a default timeout or allow specifying a requests timeout (and number of retries) as an argument to the query method?

**Comment by nassibnassar** [comment]
New functions [set_okapi_max_retries()](https://library-data-platform.github.io/ldlite/ldlite.html#LDLite.set_okapi_max_retries) and [set_okapi_timeout()](https://library-data-platform.github.io/ldlite/ldlite.html#LDLite.set_okapi_timeout) added in v0.0.31
